### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by ValentinJesse** [knoopx/poloniex-watch#2]
Hi!

After running into a dependency horror for countless hours with npm/node/vs, i have finally managed to install the app on windows. (Should've package it with Docker)

Now, the thing is that, although it successfully launched the server instance at localhost:3000, the application simply does not want to run, giving me the "Cannot GET" error in browser. 

I see that there's also a missing style.css that was supposed to be in the dist folder. Are those images a mockup or they represent screenshots from the actual app ?

Thanks!

**Comment by ValentinJesse** [comment]
I also receive these errors when i run npm run dev

![2016-11-02_06-57-06_npm](https://cloud.githubusercontent.com/assets/7979136/19917194/aa0fa904-a0c9-11e6-8b80-bc8dda18e4ca.png)

**Comment by knoopx** [comment]
hi @ValentinJesse, yes the app works and the screenshots are real, however deps were broken at the time you tried it. I've updated/fixed deps and everything should be fine now, just pull and follow the instructions in the README. 

Note that this an Electron-based app, and it will not work in your browser. When you run `npm run development` the app should start minimized in your tray bar, however I've not tried it on Windows and may not properly work.

**Comment by ValentinJesse** [comment]
Thanks for the support!

Unfortunately, when i run "npm run development", i receive:

`c:\polo>npm run development

> poloniex-watch@0.1.0 development c:\polo
> cross-env NODE_ENV=development concurrently --kill-others "npm run dev-server" "npm run start"

[0]
[0] > poloniex-watch@0.1.0 dev-server c:\polo
[0] > webpack-dev-server --hot --inline --config webpack.config.$NODE_ENV.js
[0]
[1]
[1] > poloniex-watch@0.1.0 start c:\polo
[1] > electron .
[1]
[1]
[0] module.js:471
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module 'c:\polo\webpack.config.$NODE_ENV.js'
[0]     at Function.Module._resolveFilename (module.js:469:15)
[0]     at Function.Module._load (module.js:417:25)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at module.exports (c:\polo\node_modules\webpack\bin\convert-argv.js:80:13)
[0]     at Object.<anonymous> (c:\polo\node_modules\webpack-dev-server\bin\webpack-dev-server.js:68:48)
[0]     at Module._compile (module.js:570:32)
[0]     at Object.Module._extensions..js (module.js:579:10)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]
[0] npm
[0]  ERR! Windows_NT 10.0.10586
[0] npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev-server"
[0] npm ERR! node v6.9.1
[0] npm ERR! npm  v3.10.9
[0] npm
[0]  ERR! code ELIFECYCLE
[0] npm ERR! poloniex-watch@0.1.0 dev-server: `webpack-dev-server --hot --inline --config webpack.config.$NODE_ENV.js`
[0] npm ERR! Exit status 1
[0] npm ERR!
[0] npm ERR! Failed at the poloniex-watch@0.1.0 dev-server script 'webpack-dev-server --hot --inline --config webpack.config.$NODE_ENV.js'.
[0] npm ERR! Make sure you have the latest version of node.js and npm installed.
[0] npm ERR! If you do, this is most likely a problem with the poloniex-watch package,
[0] npm ERR! not with npm itself.
[0] npm ERR! Tell the author that this fails on your system:
[0] npm ERR!     webpack-dev-server --hot --inline --config webpack.config.$NODE_ENV.js
[0] npm ERR! You can get information on how to open an issue for this project with:
[0] npm ERR!     npm bugs poloniex-watch
[0] npm ERR! Or if that isn't available, you can get their info via:
[0] npm ERR!     npm owner ls poloniex-watch
[0] npm ERR! There is likely additional logging output above.
[0]
[0] npm ERR! Please include the following file with any support request:
[0] npm ERR!     c:\polo\npm-debug.log
[0] npm run dev-server exited with code 1
--> Sending SIGTERM to other processes..
[1] npm run start exited with code 1

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "development"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! poloniex-watch@0.1.0 development: `cross-env NODE_ENV=development concurrently --kill-others "npm run dev-server" "npm run start"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poloniex-watch@0.1.0 development script 'cross-env NODE_ENV=development concurrently --kill-others "npm run dev-server" "npm run start"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the poloniex-watch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development concurrently --kill-others "npm run dev-server" "npm run start"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs poloniex-watch
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls poloniex-watch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\polo\npm-debug.log`

**Comment by knoopx** [comment]
Windows probably does not play well with ENV vars, try replacing `$NODE_ENV` in `package.json` with `development`

**Comment by ValentinJesse** [comment]
Thanks! It's finally working, although the Electron instance is pretty minimalistic (can't move it at all and stays on top of every other window by default)

I was so eager to install it because i liked how you designed the left panel with all the charts for each cryptocurrency. I'm looking to build my own version of poloniex, so this could serve as an inspiration.  The app looks pretty clean as well. Nice job
